/**
 * System constants
 */

export const SYSTEM_CLOSE_ALERT = 'SYSTEM_CLOSE_ALERT'
export const SYSTEM_CLOSE_NOTIFICATIONS = 'SYSTEM_CLOSE_NOTIFICATIONS'

/**
 * User auth constants
 */
export const USER_AUTH = 'USER_AUTH'

/**
* My constants
*/

export const MY_PROFILE_REQUEST = 'MY_PROFILE_REQUEST';
export const MY_PROFILE_RESPONSE = 'MY_PROFILE_RESPONSE';
export const MY_PROFILE_RESPONSE_ERROR = 'MY_PROFILE_RESPONSE_ERROR';

export const MY_NOTIFICATIONS_REQUEST = 'MY_NOTIFICATIONS_REQUEST';
export const MY_NOTIFICATIONS_RESPONSE = 'MY_NOTIFICATIONS_RESPONSE';
export const MY_NOTIFICATIONS_RESPONSE_ERROR = 'MY_NOTIFICATIONS_RESPONSE_ERROR';

export const MY_NOTIFICATIONS_READ_REQUEST = 'MY_NOTIFICATIONS_READ_REQUEST';
export const MY_NOTIFICATIONS_READ_RESPONSE = 'MY_NOTIFICATIONS_READ_RESPONSE';
export const MY_NOTIFICATIONS_READ_RESPONSE_ERROR = 'MY_NOTIFICATIONS_READ_RESPONSE_ERROR';

export const MY_FRIENDS_INBOX_REQUEST = 'MY_FRIENDS_INBOX_REQUEST';
export const MY_FRIENDS_INBOX_RESPONSE = 'MY_FRIENDS_INBOX_RESPONSE';
export const MY_FRIENDS_INBOX_ERROR = 'MY_FRIENDS_INBOX_ERROR';

export const MY_FRIENDS_OUTBOX_REQUEST = 'MY_FRIENDS_OUTBOX_REQUEST';
export const MY_FRIENDS_OUTBOX_RESPONSE = 'MY_FRIENDS_OUTBOX_RESPONSE';
export const MY_FRIENDS_OUTBOX_ERROR = 'MY_FRIENDS_OUTBOX_ERROR';

export const ADD_FRIEND_REQUEST = 'ADD_TO_FRIEND_REQUEST';
export const ADD_FRIEND_RESPONSE = 'ADD_TO_FRIEND_RESPONSE';
export const ADD_FRIEND_ERROR = 'ADD_TO_FRIEND_ERROR';

export const REMOVE_FRIEND_REQUEST = 'REMOVE_FRIEND_REQUEST';
export const REMOVE_FRIEND_RESPONSE = 'REMOVE_FRIEND_RESPONSE';
export const REMOVE_FRIEND_ERROR = 'REMOVE_FRIEND_ERROR';


/**
 * Common user constants
 */

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RESPONSE = 'USER_PROFILE_RESPONSE';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

export const USER_FRIENDS_REQUEST = 'USER_FRIENDS_REQUEST';
export const USER_FRIENDS_RESPONSE = 'USER_FRIENDS_RESPONSE';
export const USER_FRIENDS_ERROR = 'USER_FRIENDS_ERROR';

export const USER_PROFILE_MATCHES_REQUEST = 'USER_PROFILE_MATCHES_REQUEST';
export const USER_PROFILE_MATCHES_RESPONSE = 'USER_PROFILE_MATCHES_RESPONSE';
export const USER_PROFILE_MATCHES_ERROR = 'USER_PROFILE_MATCHES_ERROR';


/**
 * Mix & Match constants
 */

export const MIX_SEARCH_REQUEST = 'MIX_SEARCH_REQUEST';
export const MIX_SEARCH_RESPONSE = 'MIX_SEARCH_RESPONSE';
export const MIX_SEARCH_ERROR = 'MIX_SEARCH_ERROR';

export const MIX_CONFIRMATION_TICK = 'MIX_CONFIRMATION_TICK';

export const MATCH_FORMATS_REQUEST = 'MATCH_FORMATS_REQUEST_STARTED';
export const MATCH_FORMATS_RESPONSE = 'MATCH_FORMATS_REQUEST_FINISHED';
export const MATCH_FORMATS_ERROR = 'MATCH_FORMATS_REQUEST_ERROR';

export const MATCH_REQUEST = 'MATCH_REQUEST';
export const MATCH_RESPONSE = 'MATCH_RESPONSE';
export const MATCH_RESPONSE_ERROR = 'MATCH_RESPONSE_ERROR';

export const MATCHES_REQUEST = 'MATCHES_REQUEST';
export const MATCHES_RESPONSE = 'MATCHES_RESPONSE';
export const MATCHES_RESPONSE_ERROR = 'MATCHES_RESPONSE_ERROR';


/**
 * Comments constants
 */
export const COMMENTS_LIST_REQUEST = 'COMMENTS_LIST_REQUEST';
export const COMMENTS_LIST_RESPONSE = 'COMMENTS_LIST_RESPONSE';
export const COMMENTS_LIST_ERROR = 'COMMENTS_LIST_ERROR';

export const COMMENTS_ADD_REQUEST = 'COMMENTS_ADD_REQUEST';
export const COMMENTS_ADD_RESPONSE = 'COMMENTS_ADD_RESPONSE';
export const COMMENTS_ADD_ERROR = 'COMMENTS_ADD_ERROR';
