export const MIX_STATUS_AVAILABLE = 'MIX_STATUS_AVAILABLE';
export const MIX_STATUS_UNAVAILABLE = 'MIX_STATUS_UNAVAILABLE';
export const MIX_STATUS_SEARCHING = 'MIX_STATUS_SEARCHING';

export const MIX_NEED_CONFIRMATION = 'MIX_NEED_CONFIRMATION';
export const MIX_WAS_CANCELED = 'MIX_WAS_CANCELED';

export const MIX_WAS_CONFIRMED_BY_USER = 'MIX_WAS_CONFIRMED_BY_USER';
export const MIX_WAS_CANCELED_BY_USER = 'MIX_WAS_CANCELED_BY_USER';

export const MIX_STATUS_UPDATE = 'MIX_STATUS_UPDATE';
export const MIX_MATCH_CREATED = 'MIX_MATCH_CREATED';
export const MIX_MATCH_FOUND = 'MIX_MATCH_FOUND';

export const MIX_CREATE_SEARCH_REQUEST = 'MIX_CREATE_SEARCH_REQUEST';
export const MIX_CREATE_SEARCH_RESPONSE = 'MIX_CREATE_SEARCH_RESPONSE';
export const MIX_CANCEL_SEARCH_REQUEST = 'MIX_CANCEL_SEARCH_REQUEST';
export const MIX_CANCEL_SEARCH_RESPONSE = 'MIX_CANCEL_SEARCH_RESPONSE';



